name: Build Stockfish

on:
  push:
    tags:
      - 'v*'  # Kích hoạt khi bạn tạo tag như v1.0, v2.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ make

    - name: Build Stockfish
      run: |
        cd src
        make build ARCH=x86-64-modern
        cp stockfish ../stockfish-linux

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: stockfish-linux
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
